-- Active: 1767840773547@@127.0.0.1@3306@aloha
CREATE TABLE `todo` (
    `no` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'PK',
    `id` VARCHAR(64) NOT NULL COMMENT 'UK',
    `name` TEXT NOT NULL COMMENT '할일',
    `status` BOOLEAN NOT NULL DEFAULT false COMMENT '상태',
    `seq` INT NOT NULL DEFAULT 0 COMMENT '순서',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자'
);

SELECT * FROM todo;